### ISSUE TITLE
Tap and Click

### ISSUE THREAD

**Issue by lesarnott** [nolimits4web/Swiper#1115]
I've seen the following issues with tap and click using the "Thumbs Gallery With Two-way Control" demo.  On an HP ENVY 15t under Windows 8.1, I'm testing tap on the touch screen, then mouse  click on thumbs to ensure it selects a slide in the main gallery: 

Chrome 40.0.2214.115 
  tap works     click does nothing
 
IE 11.0.9600.17631
  tap does nothing   click works

Firefox 35.0.1
  tap works     click works

Safari 5.1.7 (7534.57.2)
  tap works     click works

I also tested IE and Chrome on an ASUS T200 tablet and saw the same results

**Comment by nolimits4web** [comment]
You have ie device with both touch and mouse inputs?

**Comment by lesarnott** [comment]
Yes, the HP Envy laptop has a touch screen and the ASUS is a tablet with a detachable keyboard.

**Comment by nolimits4web** [comment]
Could you please try it with latest dev version

**Comment by nolimits4web** [comment]
This should be fixed in dev version, could you please check it?

**Comment by lesarnott** [comment]
Sorry for the delay, I had to install nodejs etc to do the build.  Thanks for the fix.   Yes, both tap and click are now working on Chrome but tap is still not working on IE.

Testing IE, I set a breakpoint at line 1175 in swiper.js

            // Tap, doubleTap, Click
            if (s.allowClick) {

I tapped on a thumb, it hit the breakpoint and I changed s.allowClick from false to true and then the tap worked ok.

Anything else you'd like me to try?

Les

**Comment by nolimits4web** [comment]
Thanks. By not working tap you mean when you tap gallery thumb with finger over screen?

**Comment by lesarnott** [comment]
Yes,  I'm only talking about problems with tap/click on the thumbs gallery to select a photo in the main gallery.  After your fix the only remaining problem I'm seeing is on IE when tapping with a finger on a thumb gallery photo.

**Comment by lesarnott** [comment]
Any update on this?   More evidence of the problem - in IE none of the demos on your web site respond to taps on the next/prev arrows, pagination, or carousel selection but they all respond to swipes.  With Chrome all demos respond to swipes and taps.

**Comment by nolimits4web** [comment]
Fixed right now in dev version
