### ISSUE TITLE
BUG: idangerous Swiper - Multiple nested vertical slides with fade

### ISSUE THREAD

**Issue by iforwms** [nolimits4web/Swiper#1315]
The easiest way to explain the bug is by showing you, check out this fiddle:

https://jsfiddle.net/iforwms/a13fgzdm/13/

Sliding to slide number 2 and sliding up and down through the nested vertical slides results in the third set of slides being scrolled, not the current set of slides.

Regardless of how many sets of vertical slides you add, it's always the last set that get scrolled. It's an issue of the opacity I think, the browser picks up the top level div (the last one in the code) and scrolls through that, because the opacity is set to 0 but the div element is still there.

Changing line 5 of the javascript, removing the fade effect on the horizontal slide removes the issue.

**Comment by nolimits4web** [comment]
Fixed, thanks!

**Comment by simonescalbi** [comment]
In this case fade is still broken
https://jsfiddle.net/a13fgzdm/29/
