### ISSUE TITLE
Swiper Beta 4.0 uses the removed .use method from Dom7

### ISSUE THREAD

**Issue by emmaB93** [nolimits4web/Swiper#2225]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: Beta 4.0
* Platform/Target and Browser Versions: All Platforms

### Problem
Swiper throws an error, because you removed the .use method but using it still in swiper.modular.js Line 39.

**Comment by sebastiansulinski** [comment]
Yeah - same problem here.

**Comment by emmaB93** [comment]
Fixed with Version 4.0.0

**Comment by sebastiansulinski** [comment]
I don't think it has - I have version 4.0.0 installed and when compiling I still get the same error:

```
assets/js/front/app.js from UglifyJs
Unexpected token: name (Dom7) [./node_modules/dom7/dist/dom7.modular.js:14,0][assets/js/front/app.js:24208,6]
```

**Comment by nolimits4web** [comment]
@sebastiansulinski make sure there is a Dom7 v2.0.1 in your package.json dependencies. Also if you use ES module version, make sure you have transpiler enabled (like Babel or Buble)

**Comment by sebastiansulinski** [comment]
Thanks @nolimits4web. `dom7 v2.0.1` is included with this package as its dependency so it must be available when compiling. I'm using `laravel-mix` to compile all resources - it uses webpack with babel and some other preprocessors - it's only this specific package that squeaks this error - the moment I remove it - it all compiles just fine.
