### ISSUE TITLE
Microsoft Edge click not selecting the clicked option

### ISSUE THREAD

**Issue by WilliamStephens** [nolimits4web/Swiper#2265]
Let me know if you can't reproduce locally. I have a fix for this locally and can submit a pr if its reproducible outside of my environment but I don't have much spare time to set up a codepen. 

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 3.4.2
* Platform/Target and Browser Versions: Microsoft Edge Browser Latest but pretty sure its broken in older versions as well.

* Live Link or JSFiddle/Codepen or website with isssue: 

### What you did
Created swiper and tried to click an option

### Expected Behavior
Clicking on an option should select it

### Actual Behavior
Clicking an option doesn't select it

**Comment by nolimits4web** [comment]
Fixed in latest version

**Comment by Huooo** [comment]
Hello, nice to see you fix this question, but I still have the question when I test it by IE. Please help me and thank you very much. [example on codepen](https://codepen.io/huooo/pen/LOjqZJ)

**Comment by tsamsiyu** [comment]
Still does not work in Edge (used version 16)
https://jsfiddle.net/tsamsiyu/9t9L842u/

**Comment by tsamsiyu** [comment]
Can you reopen this please
