### ISSUE TITLE
Keyboard - navigation through slides not working

### ISSUE THREAD

**Issue by gogy27** [nolimits4web/Swiper#2380]
This is a (multiple allowed):
* [x] bug

* Swiper Version: 4.0.7
* Platform/Target and Browser Versions: Chrome 62 on Mac OS X 10
* Live Link or JSFiddle/Codepen or website with isssue: http://idangero.us/swiper/demos/

### What you did
Navigation through slides with keyboard is not working when the slider is not on the top of the page. You can see it also on your demos page: http://idangero.us/swiper/demos/
Or you can visit http://idangero.us/swiper/demos/260-keyboard-control.html directly and set `body{padding-top: 101vh;}`

### Expected Behavior
If the slider is in the viewport, it should slide with keyboard arrows.

### Actual Behavior
It doesn't slide.

I guess the problem is in the `handle` method of the `Keyboard` class, where you check if swiper is inside of visible area of window. I think you are using the `offset()` function for the `swiper.$el` wrongly, because it returns relative offset to actual viewport so you don't need to recalculate it once again in `Keyboard.handle()` method.

**Comment by spoeken** [comment]
@gogy27 did you find a fix for this?

**Comment by hacknug** [comment]
Experiencing this issue too.

**Comment by hacknug** [comment]
@nolimits4web keyboard navigation doesn't work for me when I set the `keyboard`value to `true`. The issue is resolved when I use an object instead (like with most of this properties since v4.x).

Could you please update the docs to show the right way to do it or maybe fix it so it works the way it's described there?


Right way:
```js
keyboard: {
  enabled: true,
  onlyInViewport: false
}
```

Wrong way:
```js
keyboard: true,
onlyInViewport: false
```

**Comment by gogy27** [comment]
Hi everybody,

the author's solution didn't work for me so I've made a [PR which should fix this issue](https://github.com/nolimits4web/Swiper/pull/2429).
@nolimits4web please check it once again.

**Comment by maximilianschmidt** [comment]
the fix from @hacknug worked for me. thanks!

**Comment by drpiou** [comment]
The "fix" of @hacknug (which is actually just a good reading of the documentation) actually does not fix when `onlyInViewport` is set to `true` on the `keyboard` object.

This is working fine:
```
keyboard: {
  enabled: true,
  onlyInViewport: false,
}
```

This is not working:
```
keyboard: {
  enabled: true,
  onlyInViewport: true,
}
```

**Comment by spoeken** [comment]
Try
`      keyboard: {
        onlyInViewport: true
      },`
