### ISSUE TITLE
Usage with typescript

### ISSUE THREAD

**Issue by atilkan** [nolimits4web/swiper#2619]
How can i import and use Swiper with typescript setup with webpack and ts-loader.
It throws this if i try to interact with container.
![screen shot 2018-05-11 at 16 22 02](https://user-images.githubusercontent.com/1254613/39926368-aba99242-5537-11e8-86b6-90acea543c70.png)

```
import Swiper from "swiper"

new Swiper("#landingSlider", {
         direction: "vertical",
})
```

**Comment by nolimits4web** [comment]
Make sure you run Babel over Swiper esm module http://idangero.us/swiper/get-started/

**Comment by atilkan** [comment]
@nolimits4web that is the issue. I dont use babel.

**Comment by nolimits4web** [comment]
Then you have two because swiper ES module is not transpiled

**Comment by atilkan** [comment]
İ use typescript compiler. İs there any example for that. 
@nolimits4web

**Comment by ldoloscan** [comment]
Hello, any luck on this issue ?

**Comment by atilkan** [comment]
He doesnt seem to except babel is not the only way. 
I solved by loading compiled code with script tag. Old school.

**Comment by ldoloscan** [comment]
Hey, thanks for the response,

so what i did, I imported swiper from js directly `import * as Swiper from 'swiper/dist/js/swiper.js'`,

and in AfterInit medhod initiallized it
``
    ngAfterViewInit() {
        this.anchorsSwiper = new Swiper('.swiper-container',
            {
                slidesPerView: 'auto',
                spaceBetween: 6
            });
    }
``

now i have it working very well in Angular 5 !!

**Comment by Fenopiu** [comment]
Still not working after all this solutions.
It still giving me:
[ts] Module ''swiper'' has no default export.

**Comment by ldoloscan** [comment]
@Fenopiu I've made a Plunker, check it out: [Swiper](https://next.plnkr.co/edit/NT3Q2PWWhPfMbq5p?open=lib%2Fapp.ts&deferRun=1)

**Comment by andreaforni** [comment]
@ldoloscan I have the same problem of @Fenopiu, I tried your Plunker but I see an error in the4th line: _Cannot find module 'swiper'_.
