### ISSUE TITLE
watchOverflow and loop

### ISSUE THREAD

**Issue by ockle** [nolimits4web/swiper#2621]
When you have one image/element/slide, `watchOverflow: true` hides the navigation and pagination as expected. However, if you also have `loop: true` (because you want it to loop in instances where there is more than one slide), `watchOverflow` no longer has any effect. I guess the `watchOverflow` calculation isn't done before the additional/duplicate slides are inserted for the loop effect.

**Comment by Togetic** [comment]
same problem

**Comment by franckichmish** [comment]
same for me

**Comment by kireerik** [comment]
I am not using `watchOverflow` with `loop`, but I think this issue makes sense. So we should open this issue.

@nolimits4web What do you think?

**Comment by vstetsenko1904** [comment]
Same for me. 
Loop always duplicates slides even number of slides less than slidesPerView.
This is very big problem for me.
@nolimits4web any update ?

**Comment by saboshi69** [comment]
Same for me

**Comment by WitoTV** [comment]
@nolimits4web any update on this?

**Comment by jonasmarco** [comment]
Any news?
It's a big problem :(

**Comment by muratdogan17** [comment]
Different day, same problem :/

**Comment by durchanek** [comment]
Unfortunately, @nolimits4web explained in #2900 this is considered a feature, so I wouldn't expect it to change anytime soon. In my humble opinion, I can't se any use case in which you want to have three same images looping around and it remained me of this picture  instead (no offence here, I still LOVE this library).
![bug-vs-feature](https://user-images.githubusercontent.com/148254/67145521-ad213c80-f29b-11e9-88d8-7211e3f756c3.jpg)

**Comment by dwickander** [comment]
Same for me - please fix - this is not a feature IMHO

**Comment by ardavan-ansari** [comment]
I doubt this will be of any help, but my issue was resolved when I removed init:false on my swiper instance.
Maybe they are somehow related?

**Comment by AlexWayfer** [comment]
This is still an issue. Please, reopen it . If you think that it's a feature — OK, let's make it configurable. For example, non-binary values:

```json
loop: true,
watchOverflow: "true-for-loop"
```

**Comment by AlexWayfer** [comment]
Work-around:

```json
loop: slidesCount > 1,
watchOverflow: true
```

**Comment by robizzt** [comment]
This is my solution.

```
var slider = document.querySelectorAll('.swiper-container')[0];
if (slider) {
	var sliderSwiper = new Swiper(slider, {
		init: false,
		// Options...
	});
	// Hide/Show pagination on initialization (and, if you have breakpoints, on resize)
	sliderSwiper.on('init resize', function() {
		var sliderRealSlides = slider.querySelectorAll('.swiper-slide:not(.swiper-slide-duplicate)'),
			sliderPagination = slider.querySelectorAll('.swiper-pagination')[0];
		console.log(sliderRealSlides.length, this.params.slidesPerView, this);
		if (sliderRealSlides.length <= this.params.slidesPerView) {
			sliderPagination.style.display = 'none';
		} else {
			sliderPagination.style.display = 'block';
		}
	});
	sliderSwiper.init();
}
```

**Comment by RynerNO** [comment]
> Unfortunately, @nolimits4web explained in #2900 this is considered a feature
Fucking cunt.
