### ISSUE TITLE
Buggy swiping when using loopedSlides and slidesPerView: 'auto'

### ISSUE THREAD

**Issue by brandonce** [nolimits4web/swiper#2630]
Similar issues have been opened before but were closed without a fix. This one has an updated jsfiddle.

This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: at least as early as [3.4.0](http://idangero.us/swiper/forum/#!/bugs-and-issues:need-two-clicks-to-activate), and currently 4.2.6.
* Platform/Target and Browser Versions: macOS, CHROME (all browsers).
* Live Link or JSFiddle/Codepen or website with issue: https://jsfiddle.net/n88Lhesr/4/

### What you did
Click the right arrow button 3 times to get to slide 3, then click the left button.

### Expected Behavior
Expected: It goes back to slide 2

### Actual Behavior
Actual: Slide 2 vanishes and it stays on slide 3

(I think it's jumping to the duplicated slide 3 that exists to the far left of the "real" slides, which is the true slide index 0). Possible workaround is setting loopedSlides to the total number of slides, but this is not performant if there are numerous or complex slides. I think the index calculations that determine when to jump between duplicate slide N and real slide N need to be examined.

**Comment by kochizufan** [comment]
I believe this issue is fixed in #2651 PR.

**Comment by brandonce** [comment]
Sorry, but it looks like it is not.

Updated jsfiddle (swiper version updated to 4.3.3) : https://jsfiddle.net/n88Lhesr/8/

**Comment by cgat** [comment]
As noted by @brandonce, this is still an issue. To generalize, if you set `loopedSlides` to anything less than or equal to half of the amount of slides, you can replicate this behaviour.

**Comment by cgat** [comment]
I'm using swiper 4.4.1 for what it's worth
