### ISSUE TITLE
CSS Grid + Swiper Wrapper - wrong width calculated

### ISSUE THREAD

**Issue by edwardjosephbennett** [nolimits4web/swiper#2914]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 4.4.2 from CDNJS
* Platform/Target and Browser Versions: Latest Chrome on macOS (confirmed issue is happening in Latest Safari also)
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/anon/pen/pqJBWX
(Also raised with others: https://codepen.io/meredevelopment/pen/yorRMm and here on your forums: http://idangero.us/swiper/forum/#!/?css%20grid)

### What you did
A basic CSS grid setup with 3 columns setup on a wrapper. Carousel is set up within the 3rd column with a width of 1fr (which should take up 1fr of the remaining space of the max-width container). For code example see codepen showing issue. Code is direct replica of code in my development build.

### Expected Behavior
Swiper wrapper is to take up the remaining space of the container instead of overflowing with the correct `slidesPerView` visible

### Actual Behavior
Swiper wrapper is overflowing, with `slidersPerView` being ignored. Wrapper is showing width of entire width of elements.

**Comment by nolimits4web** [comment]
In such layout, there is no clear way in this case to detect available "cell" width -> so swiper can't calculate its own and slides size. You can fix this current layout but changing `width: 100vw` on `.carousel` or by using flex instead of grid

**Comment by mxwendt** [comment]
I had a similar issue and found a solution.

You can prevent Swiper from overflowing by adding an `overflow: hidden` to the parent element (in your case the `.wrapper`).

And there was also an issue with your grid column setup. `.sidebar` should have a value of `1 / 2` and `.carousel` a value of `2 / 3`.

I updated your Codepen example: https://codepen.io/anon/pen/MdmxNp

**Comment by anketwokings** [comment]
Almost a year later and grid is a best practice. It would really help if this issue would not exist anymore. :)

The fix from https://github.com/nolimits4web/swiper/issues/2914#issuecomment-493384617 worked like a charm nonetheless! 

And of course, thank you for swiper, it works really well, and kudos for the good docs!

**Comment by suxscribe** [comment]
> I had a similar issue and found a solution.
> 
> You can prevent Swiper from overflowing by adding an `overflow: hidden` to the parent element (in your case the `.wrapper`).
> 
> And there was also an issue with your grid column setup. `.sidebar` should have a value of `1 / 2` and `.carousel` a value of `2 / 3`.
> 
> I updated your Codepen example: https://codepen.io/anon/pen/MdmxNp

Your solution only works if you set width of some column in 'px'.
If columns are set in 'fr' swiper takes all the space and goes into infinity (I have 6-digit numbers in 'translate3d' property of the slides)

**Comment by ckihneman** [comment]
At the very least, there should be a "Gotchas" section, or something to that effect added to the documentation that notes this blatant issue. I can imagine many people, like myself, pulled their hair out for far, far too long thinking something was wrong with our setup.

In my case, it was a basic flex layout. Adding `overflow: hidden` to the parent did fix the issue immediately.

**Comment by rilwis** [comment]
I got the same issue and the `overflow: hidden` trick doesn't work. I think the problem is similar to what @suxscribe described. I set the layout using `fr`, not `px`.

This is my screenshot: https://prnt.sc/ry8y59

**Comment by vampics** [comment]
+1

I fixed it dirty with an width overwrite on the slides.

**Comment by migueltrias** [comment]
Still happening... Swiper goes bonkers if it's in a Grid with FR units.

**Comment by const-int** [comment]
> Still happening... Swiper goes bonkers if it's in a Grid with FR units.
> 
> When changing grid-template-columns to percentage instead fr, it works, but makes the "grid gaps" calculation more tedious this way.

Thank you, helped a lot.

**Comment by kobekoto** [comment]
+1

**Comment by rakeshshubhu** [comment]
I thought overflow is working but it doesnt seem to work, breakpoints get messed up. 
Is there any way to tackle the `fr` grid problem? .....

**Comment by arnaudjnn** [comment]
Works for me like this:

```
/** @jsx jsx */
import { jsx, Grid } from '@chakra-ui/core';
import Swiper from 'react-id-swiper';

function CarouselGrid() {

    const params = {
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    }

    return (
      <Grid gridTemplateColumns="200px auto">
        <div>
          Col Left
        </div>
        <div sx={{ width: '100%', overflow: 'hidden'}}>
          <div sx={{
            '.swiper-container': {
              width: '100%'
            },
            '.swiper-slide': {
              bg: 'gold'
            }
          }}>
            <Swiper {...params}>
              <div>Slide #1</div>
              <div>Slide #2</div>
              <div>Slide #3</div>
            </Swiper>
          </div>
        </div>
      </Grid>
    )
  }

**Comment by uldo** [comment]
instead of 'auto' in grid-column definition, you can use 'minmax(0, auto)'. the column width gets calculated in pixel, so the swiper calculates its width correctly.

**Comment by mintbird** [comment]
My workaround to solve this problem for a **single-slide slider** that placed inside flex item.

```
.swiper-slide {
    width: 100% !important;
}
```

**Comment by Plot1337** [comment]
None of the solutions listed above worked for me.

**Comment by vhoyer** [comment]
Just to contribute to the catalog of workarounds: in my case I was using only a single column in the grid, so I instead of using the default value for `  grid-template-columns`, I explicitly set it to `grid-template-columns: 100%;` and it worked wonders, thank you guys ;)

**Comment by dungle-scrubs** [comment]
One more workaround to add, as I've noticed something specific. If I have a 2-column grid (using `grid-template-columns: 1fr 1fr`), the crucial part is that the **immediate** child in the column must have `overflow: hidden`.  Then, Swiper will calculate its width correctly no matter how far nested it is.

- container (grid, two columns)
  - div (100% width, overflow hidden)
    - div
      - div
        - swiper

If the immediate child of the column is not set to overflow hidden, the width won't be calculated correctly 

This will break:

- container (grid, two columns)
  - div 
    - div
      - div (100% width, overflow hidden)
        - swiper

**Comment by Janchey** [comment]
@dungle-scrubs That looks like something that might work for me. Just need on some more info on this. I will need to have something like this in order for swiper to calculate thing right:

- container (grid, grid tempate columnd 1fr 1fr)
- div (grid column span 1, 100% width, overflow hidden)
- swiper

or is it more like this:
- container (grid, two columns)
- div (grid column span 1)
- div (100% width, overflow hidden)
- swiper

**Comment by dungle-scrubs** [comment]
> @dungle-scrubs That looks like something that might work for me. Just need on some more info on this. I will need to have something like this in order for swiper to calculate thing right:
> 
> * container (grid, grid tempate columnd 1fr 1fr)
> * div (grid column span 1, 100% width, overflow hidden)
> * swiper
> 
> or is it more like this:
> 
> * container (grid, two columns)
> * div (grid column span 1)
> * div (100% width, overflow hidden)
> * swiper

I believe that the second one you mentioned will break.  For me, the immediate grid-child must have the `overflow: hidden` property, but I'm not sure why it's behaving that way.

Have you had any luck?

**Comment by levazver** [comment]
Right now solution is using `minmax(0, 1fr)` instead of `1fr`.

**Comment by aaronchristian99** [comment]
It's useless to swiper if it doesn't work with grid very well. Using `overflow: hidden` is a hack and a solution. Swiper is good on desktop when using `display: grid` but when doing responsive it doesn't work very well

**Comment by janekth** [comment]
For me, it worked to wrap the slider with an additional `display: grid` element and set swiper-container to 100% width.
codepen as demo: [](https://codepen.io/_Mellow/pen/KKmRwzw)

**Comment by francosalcedo** [comment]
> Solo para contribuir al catálogo de soluciones: en mi caso, estaba usando solo una columna en la cuadrícula, así que en lugar de usar el valor predeterminado para ` grid-template-columns`, lo configuré explícitamente `grid-template-columns: 100%;`y funcionó de maravilla, gracias chicos;)

Very thanks! its work!

**Comment by radum** [comment]
I had 2 different scenarios, both kind of relating to what I raised in #4993

**Scenario 1**

Parent element with display grid and 1 column. Swiper deep nested inside of it.

```
.parent {
  display: grid;
  grid-template-rows: 16px;
}
```

The problem here across all browsers was that swiper didn't calculate the width properly so each slide was causing a horizontal scroll by pushing the container. To solve it I also added `grid-template-columns: 100%;` to the `.parent`.

Another fix I did for this before was to wrap swiper in another grid and that seemed to do the trick. But that has an issue that I will explain bellow.

**Scenario 2**

Parent element with display grid and multiple columns. Swiper nested 2 levels down in the `.col` element.

```
.parent {
  display: grid;
  grid-template-rows: repeat(var(--rows, 1), 1fr);
  grid-template-columns: repeat(var(--columns, 12), 1fr);
  gap: var(--gap, 16px);
}

.parent .col {
  grid-column: auto/span 6;
}
```

In this case Chrome is fine, but on Firefox Swiper will grow to infinity without stoping. To fix this I had to change the template columns to `grid-template-columns: repeat(var(--columns, 12), minmax(0, 1fr));`.

Initially to solve this issue was to disable the resize observer in settings. Seems that the observer triggers all the time.

**Comment by SvenBudak** [comment]
> At the very least, there should be a "Gotchas" section, or something to that effect added to the documentation that notes this blatant issue. I can imagine many people, like myself, pulled their hair out for far, far too long thinking something was wrong with our setup.
> 
> In my case, it was a basic flex layout. Adding `overflow: hidden` to the parent did fix the issue immediately.

Thank you for this info! i am wondering why this issue is unfixed sience 3 years :D

**Comment by radum** [comment]
This https://youtu.be/mlmADytUiiw?list=PLGhijupHuLxJ4zJCUJcaLwEQSvQKdq-ta&t=504 explains what is happening and why is by design.

**Comment by px2code** [comment]
++
Suffer the problem with display: flex

**Comment by mbcod3** [comment]
wasted hours until found the display grid on parent was growing swiper width and some times height to infinity. Used this to fix it but feels scared what if people get that bug in their browser or device for whatever reason

`
    display: grid;
    grid-template-columns: minmax(0, 1fr);

`

**Comment by radum** [comment]
Is not a bug, that is how the [browser works](https://github.com/nolimits4web/swiper/issues/2914#issuecomment-994581280). It was a learning experience for me also.

**Comment by fweth** [comment]
I got the issue with grid-rows instead of grid-columns, I understand that that computing the column width can be difficult for the swiper, but with rows I can't see a logical issue.  I use grid for the base layout, reserving the space for header, maind and footer respectively, it should have nothing to do with the width of the corresponding elements.

**Comment by dasarwarshubham** [comment]
The issue is, when the breakpoint changes, `.swiper-grid` class gets removed automatically.
My workaround was to manually add below css class to `.swiper` class.
`
.swiper {
  & > .swiper-wrapper {
    flex-wrap: wrap !important;
  }
}
`

**Comment by babakfp** [comment]
Can we have a functionality to support this feature?

```
grid-template-columns: repeat(auto-fill,minmax(9rem,1fr))
```

It will be freaking awesome. Let me explain how it works. Let's start with the smallest screen. You are going to have 1 `slidesPerView`. Slide min-width is `9rem`. Now we are increasing the width of the device. If there was a space available to put 2 slides (+ `spaceBetween` ), then `slidesPerView` will be equal to 2 and you will see 2 slides; If not, the single slide just gets bigger because we gave it `max-width: 1fr`.
That's it.
Thank you very much for creating this awesome library🌷🌷

**Comment by magdasokolovic** [comment]
> My workaround to solve this problem for a **single-slide slider** that placed inside flex item.
> 
> ```
> .swiper-slide {
>     width: 100% !important;
> }
> ```
> 
> Tested in Swiper 6.4.8

this worked for me!

**Comment by foinf** [comment]
> One more workaround to add, as I've noticed something specific. If I have a 2-column grid (using `grid-template-columns: 1fr 1fr`), the crucial part is that the **immediate** child in the column must have `overflow: hidden`. Then, Swiper will calculate its width correctly no matter how far nested it is.
> 
> * container (grid, two columns)
>   
>   * div (100% width, overflow hidden)
>     
>     * div
>       
>       * div
>         
>         * swiper
> 
> If the immediate child of the column is not set to overflow hidden, the width won't be calculated correctly
> 
> This will break:
> 
> * container (grid, two columns)
>   
>   * div
>     
>     * div
>       
>       * div (100% width, overflow hidden)
>         
>         * swiper

This is the one that fixes swiper slider from making wrong calculations in the order of exponents.

**Comment by ShahriarKh** [comment]
> Right now solution is using `minmax(0, 1fr)` instead of `1fr`.

You are a lifesaver! Thanks.

**Comment by malipetek** [comment]
I have a workaround like this
```JS
import Swiper, { Thumbs, Zoom } from 'swiper';

window.Swiper = Swiper;
const ResizeModule = Swiper.prototype.__modules__.find(m => m.name == 'Resize');

function CustomResize(_ref) {
  console.log('using curtom resize');
  let {
    swiper,
    on,
    emit
  } = _ref;
  let observer = null;
  let animationFrame = null;

  const resizeHandler = () => {
    if (!swiper || swiper.destroyed || !swiper.initialized) return;
    emit('beforeResize');
    emit('resize');
  };

  const createObserver = () => {
    if (!swiper || swiper.destroyed || !swiper.initialized) return;
    observer = new ResizeObserver(entries => {
      animationFrame = window.requestAnimationFrame(() => {
        const {
          width,
          height,
          params
        } = swiper;
        let newWidth = width;
        let newHeight = height;
        entries.forEach(_ref2 => {
          let {
            contentBoxSize,
            contentRect,
            target
          } = _ref2;
          if (target && target !== swiper.el) return;
          newWidth = contentRect ? contentRect.width : (contentBoxSize[0] || contentBoxSize).inlineSize;
          newHeight = contentRect ? contentRect.height : (contentBoxSize[0] || contentBoxSize).blockSize;
        });

        if (Math.round(newWidth) !== Math.round(width + (swiper.params.direction == 'horizontal' ? params.spaceBetween : 0)) || Math.round(newHeight) !== Math.round(height + (swiper.params.direction == 'vertical' ? params.spaceBetween : 0))) {
          resizeHandler();
        }
      });
    });
    observer.observe(swiper.el);
  };

  const removeObserver = () => {
    if (animationFrame) {
      window.cancelAnimationFrame(animationFrame);
    }

    if (observer && observer.unobserve && swiper.el) {
      observer.unobserve(swiper.el);
      observer = null;
    }
  };

  const orientationChangeHandler = () => {
    if (!swiper || swiper.destroyed || !swiper.initialized) return;
    emit('orientationchange');
  };

  on('init', () => {
    if (swiper.params.resizeObserver && typeof window.ResizeObserver !== 'undefined') {
      createObserver();
      return;
    }

    window.addEventListener('resize', resizeHandler);
    window.addEventListener('orientationchange', orientationChangeHandler);
  });
  on('destroy', () => {
    removeObserver();
    window.removeEventListener('resize', resizeHandler);
    window.removeEventListener('orientationchange', orientationChangeHandler);
  });
}

Swiper.prototype.__modules__ = Swiper.prototype.__modules__.map(m => /Resize/.test(m.name) ? CustomResize : m);

Swiper.use([Thumbs, Zoom]);
export default Swiper;
```

This change is making it not go into loop when it has a `spaceBetween` value. Not sure if this is a proper fix tho it just fixed a case for me.
```diff
-         if ( newWidth !== width || newHeight !== height ) {
+         if (Math.round(newWidth) !== Math.round(width + (swiper.params.direction == 'horizontal' ? params.spaceBetween : 0)) || Math.round(newHeight) !== Math.round(height + (swiper.params.direction == 'vertical' ? params.spaceBetween : 0))) {

```

**Comment by dangelion** [comment]
So, in place of this
`grid-template-columns: 6fr 6fr;`

I used this
`grid-template-columns: minmax(0, 6fr) minmax(0, 6fr);`

and it worked.

**Comment by Algram** [comment]
@foinf Thanks for your suggestion. This fixes the issue for me without breaking the width calculations!

**Comment by dnntung** [comment]
> One more workaround to add, as I've noticed something specific. If I have a 2-column grid (using `grid-template-columns: 1fr 1fr`), the crucial part is that the **immediate** child in the column must have `overflow: hidden`. Then, Swiper will calculate its width correctly no matter how far nested it is.
> 
> * container (grid, two columns)
>   
>   * div (100% width, overflow hidden)
>     
>     * div
>       
>       * div
>         
>         * swiper
> 
> If the immediate child of the column is not set to overflow hidden, the width won't be calculated correctly
> 
> This will break:
> 
> * container (grid, two columns)
>   
>   * div
>     
>     * div
>       
>       * div (100% width, overflow hidden)
>         
>         * swiper

This worked for me, thank you so much

**Comment by kholmanskykh** [comment]
> wasted hours until found the display grid on parent was growing swiper width and some times height to infinity. Used this to fix it but feels scared what if people get that bug in their browser or device for whatever reason
> 
> 
> 
> `display: grid;
> 
>     grid-template-columns: minmax(0, 1fr);`

After couple of hours, found this one and it worked for me, thanks

**Comment by amirlourch** [comment]
> I had this problem on iOS 12 but `overflow: hidden` wasn't enough.
> 
> So, in place of this `grid-template-columns: 6fr 6fr;`
> 
> I used this `grid-template-columns: minmax(0, 6fr) minmax(0, 6fr);`
> 
> and it worked.

it works perfectly

i owe you

**Comment by kraftdorian** [comment]
Very helpful content here, thanks! Adding my case here if anyone will have sth similar

```jsx
<Grid> // grid-template-areas set, display grid
  <GridArea1> // grid-area set, display block. contains Swiper
    <Swiper />
  </GridArea1>
  <GridArea2 /> // grid-area set, display block
  <GridArea3 /> // grid-area set, display block
</Grid>
```

The solution was to add this to ```GridArea1``` styles - the element is a block itself, but is a part of the grid:

```css
min-width: 0;
```

Was able to come up with after reading [this StackOverflow answer](https://stackoverflow.com/questions/43311943/prevent-content-from-expanding-grid-items/43312314#43312314).
