### ISSUE TITLE
Infinite-loop navigation bug

### ISSUE THREAD

**Issue by sirvadim** [nolimits4web/swiper#3126]
* [x] bug

* Swiper Version: 4.5.0.
* Platform/Target and Browser Versions: macOS High Sierra 10.13.6, Google Chrome 75.0.3770.100

video: https://www.youtube.com/watch?v=Vx1W1YWQRpk
time code: 05 - 06, 08 - 09

Sometimes, when I click navigation buttons, it works to the opposite side.

**Comment by BananaAcid** [comment]
same on windows.

**Comment by robpop** [comment]
I've experienced this same bug in my own projects, i'll take a look at it.

**Comment by robpop** [comment]
I've made a pull request which should fix this issue @ #3237

**Comment by simmonsr** [comment]
@robpop Tried adding your fix, but still experiencing issues as shown in that video

**Comment by robpop** [comment]
@simmonsr Can you provide me with a JSFiddle or CodePen of your test, it'll make it easier for me to see where the issue is

**Comment by simmonsr** [comment]
It's via our theme, but I tried adding your code and it doesn't help. As @sirvadim pointed out though, it can be replicated via the Swiper demo too:

https://swiperjs.com/demos/200-infinite-loop.html

**Comment by robpop** [comment]
I create this Plunker, which is a copy of the demo you provided. I added in my change under the swiper.js, and commented "robpop" right above it to make it easy to find. This change still allows for short swipes, but should prevent them from firing off if the event target for the onTouchEnd event is either of those arrows:

https://plnkr.co/edit/1QlfdfMKiYKIDR2VLntQ?p=preview

Are you still experiencing this issue?

**Comment by simmonsr** [comment]
Again, using Chrome MacOS if you click on arrows Prev/Next at random, it will sometimes not move in the proper direction.

**Comment by simmonsr** [comment]
Still experience this issue here:

https://plnkr.co/edit/1QlfdfMKiYKIDR2VLntQ?p=preview

@sirvadim may also

**Comment by simmonsr** [comment]
Newest release of Swiper is helping the issue though (only able to replicate once, rather than multiple times in one session)

**Comment by simmonsr** [comment]
Less frequent it seems anyway :)
