### ISSUE TITLE
When the first screen width>=769 after applying breakpoints, the slide loops only in the previous direction only on the 769 screen

### ISSUE THREAD

**Issue by awt0523** [nolimits4web/swiper#3795]
I accidentally mentioned another issue to make it look like it solved the problem.
So I re-registered as a problem.
This has not been resolved.

I'm working in the next ssr environment.
When width is over 769 slidesPerView:3, slidesPerGroup:3 When it is less than 768 slidesPerView:1
When changing options due to breakpoints
When the first screen is width>=769 The loop only works on the previous button.
***
I made an example with react, but the same problem occurred
https://codesandbox.io/s/friendly-mclaren-molvn?file=/src/App.js
***
```
      <Swiper
        className="stay_list"
        slidesPerView={1}
        slidesPerGroup={1}
        navigation
        breakpoints={{
          769: {
            slidesPerGroup: 3,
            slidesPerView: 3,
          },
        }}
        loop
        pagination={{
          type: "fraction",
          clickable: true,
        }}
      >
```
Expected Behavior
Loop the slide with the next button
Actual Behavior
Only when the first screen is width> = 769 Slide loop only with previous button

**Comment by nolimits4web** [comment]
Same as #3794 which is fixed in src

**Comment by awt0523** [comment]
> src에서 수정 된 [# 3794](https://github.com/nolimits4web/swiper/issues/3794) 와 동일

### The content is the same as #3794, but the problem was not resolved and I did not receive an answer.

***It is my mistake to refer to #3790, which is closed on #3794.***

Please check the contents and answer

**Comment by awt0523** [comment]
> Same as #3794 which is fixed in src

@nolimits4web 
### The content is the same as #3794, but the problem was not resolved and I did not receive an answer.

***It is my mistake to refer to #3790, which is closed on #3794.***

Please check the contents and answer
