### ISSUE TITLE
Multiple swiper sliders on page reduce performance to zero in Angular

### ISSUE THREAD

**Issue by MariaLazarenko** [nolimits4web/swiper#3998]
I have multiple swiper sliders on one page in Angular and they alltogether reduce performance to zero. Initializing Swiper slider leads to thousands of change checks with every mouse move

**Comment by vltansky** [comment]
Can you provide an example?
How are you using swiper in Angular? Library?

**Comment by MariaLazarenko** [comment]
Yeah library

**Comment by vltansky** [comment]
Hey @MariaLazarenko. Swiper cant trigger change detection, probably the problem is in the Angular wrapper library (I guess you are using [ngx-swiper-wrapper](https://github.com/zefoy/ngx-swiper-wrapper). The issue probably should be moved there @nolimits4web, although it's not supported anymore.
Anyway, I'd be happy to see a stackblitz example. I tried to make some demo here, and it looks fine:
https://stackblitz.com/edit/github-xyepga-ws9xdk?file=projects%2Fapp%2Fsrc%2Fapp%2Fapp.component.ts

**Comment by MariaLazarenko** [comment]
Thanks for the reply @vltansky 
No, the thing is that I don't use ngx-swiper-wrapper actually, I'm using the pure web swiper 

Yes sure I'll will try to provide an example in a stackblitz

**Comment by vltansky** [comment]
@MariaLazarenko is this still relevant?
You can try http://swiperjs.com/angular now.

**Comment by MariaLazarenko** [comment]
@vltansky wow thanks a lot 
I'll try it

**Comment by MariaLazarenko** [comment]
btw is the new version compatible with the old one? in some places in Angular app I use the old pure version of Swiper (without any Angular wrapper). And it seems like it doesn't work now. Or maybe I'm missing smth (I've already updated link to css bundle, maybe I should update anything else?)

**Comment by vltansky** [comment]
@MariaLazarenko did you make it work?

**Comment by MariaLazarenko** [comment]
@vltansky yeah I installed it but unfortunately I faced with the same issue - multiple Swipers on page still trigger a lot of change detection checks and the page freezes and scroll doesn't work

**Comment by vltansky** [comment]
can you make a repo / stackblitz? It would really help :)

**Comment by vltansky** [comment]
#4197 this PR probably will increase performance, and will prevent ngDoCheck from firing so frequently

**Comment by vltansky** [comment]
I'm pretty sure this issue is resolved, so I'm closing the issue.
Open a new issue / comment here if any new performance issues will be met in Angular components.

**Comment by ibrahimAboelsuod** [comment]
I had the same problem and I see an improvment after updating. Rendering around 25 swipers went from around ~5s to ~3.5s -take those number with a grain of salt.

If I only display 1 slide per swiper it goes down to ~1.4s.

**Comment by francisIII** [comment]
This is still an issue at least for swipers initialized using Parameters As Props.  I think this should be reopened.

See this [bug](https://github.com/nolimits4web/swiper/issues/8049) which has a reproduciton
