### ISSUE TITLE
The slider display will inevitably break if a link, placed in one of the slides gets focused by tab key.

### ISSUE THREAD

**Issue by awacode21** [nolimits4web/swiper#4006]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Swiper Version: 5.4.5, but i guess it's relevant also for latest version as the bug also exists on swipers demo page
* Platform/Target and Browser Versions: macOS with Chrome Browser, but should be a global problem
* Live Link or JSFiddle/Codepen or website with isssue: https://codepen.io/awacode/pen/NWRxVNj
* Explanation how to fix it: https://grumpy.blog/en/js_sliders_and_the_tab_key/
* Slider which already fixed the issue can be testet here: https://grumpy.blog/en/peppermint_touch_slider/

### What you did
Use the tab key to tab through slide item links.

### Expected Behavior
Slider should show the slide item which contains the current focus as active so that it does not break the slider because browser scrolled the block to the focused element.

### Actual Behavior
Slider breaks, as its scrollLeft property has changed.
Here’s the catch: when a link hidden by overflow: hidden catches focus, browser scrolls the content of the block so you can see the link. Yes, blocks with overflow: hidden also have scrollLeft property and they act just like overflow: auto blocks.
This link describes the bug in detail and presents the needed solution to fix it: https://grumpy.blog/en/js_sliders_and_the_tab_key/
on this link https://grumpy.blog/en/peppermint_touch_slider/ you can see a slide which already uses this fix. Tab through the links within the slider and you can see.

This should definitely be fixed for the great and widely used swiper!!

Related Issues that got closed before without any solution: 
https://github.com/nolimits4web/swiper/issues/1584
https://github.com/nolimits4web/swiper/issues/290
https://github.com/nolimits4web/swiper/issues/699

**Comment by ntsim** [comment]
Taking the advice from the blog post, you can implement the fix using something like this:

```jsx
const Carousel = () => {
  const swiperRef = useRef();

  return (
    <Swiper
      onSwiper={(swiper) => {
        swiperRef.current = swiper;
      }}
    >
      <SwiperSlide
        onFocus={() => {
          if (!swiperRef.current) {
            return;
          }

          swiperRef.current.el.scrollLeft = 0;
          // Replace 0 with the slide index
          swiperRef.current?.slideTo(0);
        }}
      >
        ...
      </SwiperSlide>
    </Swiper>
  );
};
```

Of course, the ideal solution would be for Swiper to handle this automatically :smile:

**Comment by awacode21** [comment]
it is a bug of Swiper, so it should be fixed in Swiper too. I also perceived that I can work around it, but I think that is the wrong approach. Swiper is so widely used and it is an elementary bug, i guess everybody who uses swiper should also get the fix.

**Comment by banjahman** [comment]
@ntsim do you have an example of how to do this with the angular version? I've given it a few tries but can't find a good way to set the scrollLeft on the slide element.

**Comment by josh2112** [comment]
Any progress on this?

I'm running into this when using swiper with Vue and putting text inputs on my slides. I have reimplemented the workaround mentioned by @ntsim to the best of my ability in Vue 3 (composition API):

```
<script setup lang="ts">
import { Swiper, SwiperSlide } from "swiper/vue";
import "swiper/css";

function onSlideChanged(swiper: any) {
  swiper.el.scrollLeft = 0;

  // This is pointles because the active index hasn't changed
  swiper.slideTo(swiper.activeIndex);
}
</script>

<template>
  <swiper @slideChange="onSlideChanged">
    <swiper-slide v-for="i in [1, 2, 3, 4, 5]">
      <div>
        <input type="text" :value="i" />
      </div>
    </swiper-slide>
  </swiper>
</template>
```

But it doesn't quite work for me because

1. It only fixes the slide scroll position when you swipe, not on focus change, and
2. swiper doesn't change its slide index when the focus changes to an element on another slide, so it's still think's it's on the same slide as before the tabbing began.

Example:
 - Run the app
 - Click on the first text box
 - Hit [tab] 4 times. You're now in the text box on slide 5, and swiper's scroll position is somewhere between slides 4 and 5.
 - You can't swipe left because swiper still thinks we're at slide 1.
 - If you swipe right, you end up at slide 2 (because swiper doesn't know we're focused on slide 5 now).

How do we get swiper to understand that the slide index has changed when tabbing to a control on another slide? Possibly by watching for focus change for all input elements, walking up the DOM until we find the slide, figure out what index it is, and slide there manually? I'm not smart enough to do that.

**Comment by oreoorbitz** [comment]
The key is to focus on the swiper container element, so that you can execute a call every time an element in the swiper is focused on,then you use closest to go to a swiper slide element, then you get the index from there.

```
    swiperInstance.el.addEventListener('focus', event => {
     const swiperSlideToGoTo = getClosestSwiperSlide(event.target)
     swiperSlideToGoTo && goToSlide(swiperSlideToGoTo, this.baseSwiper)
    }, true)
```

**Comment by oreoorbitz** [comment]
This bug should be resolved in version 8.0.0

**Comment by chunglam2525** [comment]
> Any progress on this?
> 
> I'm running into this when using swiper with Vue and putting text inputs on my slides. I have reimplemented the workaround mentioned by @ntsim to the best of my ability in Vue 3 (composition API):
> 
> ```
> <script setup lang="ts">
> import { Swiper, SwiperSlide } from "swiper/vue";
> import "swiper/css";
> 
> function onSlideChanged(swiper: any) {
>   swiper.el.scrollLeft = 0;
> 
>   // This is pointles because the active index hasn't changed
>   swiper.slideTo(swiper.activeIndex);
> }
> </script>
> 
> <template>
>   <swiper @slideChange="onSlideChanged">
>     <swiper-slide v-for="i in [1, 2, 3, 4, 5]">
>       <div>
>         <input type="text" :value="i" />
>       </div>
>     </swiper-slide>
>   </swiper>
> </template>
> ```
> 
> But it doesn't quite work for me because
> 
> 1. It only fixes the slide scroll position when you swipe, not on focus change, and
> 2. swiper doesn't change its slide index when the focus changes to an element on another slide, so it still thinks it's on the same slide as before the tabbing began.
> 
> Example:
> 
> * Run the app
> * Click on the first text box
> * Hit [tab] 4 times. You're now in the text box on slide 5, and swiper's scroll position is somewhere between slides 4 and 5.
> * If you swipe left (i.e. next slide), you end up at slide 2, because swiper still thinks we were at slide 1.
> * Similarly, you can't swipe right (i.e. previous slide) because swiper still thought we were at slide 1.
> 
> How do we get swiper to understand that the slide index has changed when tabbing to a control on another slide? Possibly by watching for focus change for all input elements, walking up the DOM until we find the slide, figure out what index it is, and slide there manually? I'm not smart enough to do that.

This issue should be fixed with [v8.0.0](https://github.com/nolimits4web/swiper/releases/tag/v8.0.0) a11y changes

- a11y: automatically switch slides on focus (Tab) in inactive slides ([1288271](https://github.com/nolimits4web/Swiper/commit/128827156b0f125a5f6ecf1409add4146fa3c989)), closes https://github.com/nolimits4web/Swiper/issues/3149

```
<script setup lang="ts">
import { Swiper, SwiperSlide } from "swiper/vue";
import "swiper/css";
import { A11y } from "swiper";
</script>

<template>
  <swiper
    :modules="[A11y]"
    :a11y="{
      enabled: true,
    }"
  >
    <swiper-slide v-for="i in [1, 2, 3, 4, 5]">
      <div>
        <input type="text" :value="i" />
      </div>
    </swiper-slide>
  </swiper>
</template>
```

**Comment by mediaformat** [comment]
This is still an issue with Swiper v9
https://codepen.io/MediaFormat/full/qBMZeaW

**Comment by ankursehdev** [comment]
any ETA on this? This is still an issue in v9

**Comment by mediaformat** [comment]
Essentially #3149 was closed with these 2 remaining items:

* Prevent tabbing to focusable items within out-of-view slides
* Make sure disabled controls/buttons are not focusable

**Comment by mediaformat** [comment]
In the mean time I'd recommend https://github.com/Splidejs/splide

**Comment by claygriffiths** [comment]
We ran into this as well. Adding the `inert` attribute to any slides outside of the active slide resolved this issue: https://html.spec.whatwg.org/multipage/interaction.html#the-inert-attribute

**Comment by anneria** [comment]
We solved this issue with [focusin](https://developer.mozilla.org/en-US/docs/Web/API/Element/focusin_event) and passing the index.
Also works great with the keyboard module enabled.

```
<script setup lang="ts">
import { Keyboard } from 'swiper/modules';

const mainSwiper = ref<SwiperClass>();

const onSlideFocus = (index: number) => {
    mainSwiper.value?.slideTo(index);
};
</script>
 
<template>
    <swiper
        :modules="[Keyboard]"
        :keyboard="{
            enabled: true,
            onlyInViewport: true,
        }">
        <swiper-slide
            v-for="(item, index) in Items"
            @focusin="() => onSlideFocus(index)">
            <nuxt-link>link</nuxt-link>
        </swiper-slide>
    </swiper>
</template>
```

**Comment by cferdinandi** [comment]
> > Any progress on this?
> > I'm running into this when using swiper with Vue and putting text inputs on my slides. I have reimplemented the workaround mentioned by @ntsim to the best of my ability in Vue 3 (composition API):
> > ```
> > <script setup lang="ts">
> > import { Swiper, SwiperSlide } from "swiper/vue";
> > import "swiper/css";
> > 
> > function onSlideChanged(swiper: any) {
> >   swiper.el.scrollLeft = 0;
> > 
> >   // This is pointles because the active index hasn't changed
> >   swiper.slideTo(swiper.activeIndex);
> > }
> > </script>
> > 
> > <template>
> >   <swiper @slideChange="onSlideChanged">
> >     <swiper-slide v-for="i in [1, 2, 3, 4, 5]">
> >       <div>
> >         <input type="text" :value="i" />
> >       </div>
> >     </swiper-slide>
> >   </swiper>
> > </template>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But it doesn't quite work for me because
> > 
> > 1. It only fixes the slide scroll position when you swipe, not on focus change, and
> > 2. swiper doesn't change its slide index when the focus changes to an element on another slide, so it still thinks it's on the same slide as before the tabbing began.
> > 
> > Example:
> > 
> > * Run the app
> > * Click on the first text box
> > * Hit [tab] 4 times. You're now in the text box on slide 5, and swiper's scroll position is somewhere between slides 4 and 5.
> > * If you swipe left (i.e. next slide), you end up at slide 2, because swiper still thinks we were at slide 1.
> > * Similarly, you can't swipe right (i.e. previous slide) because swiper still thought we were at slide 1.
> > 
> > How do we get swiper to understand that the slide index has changed when tabbing to a control on another slide? Possibly by watching for focus change for all input elements, walking up the DOM until we find the slide, figure out what index it is, and slide there manually? I'm not smart enough to do that.
> 
> This issue should be fixed with [v8.0.0](https://github.com/nolimits4web/swiper/releases/tag/v8.0.0) a11y changes
> 
> * a11y: automatically switch slides on focus (Tab) in inactive slides ([1288271](https://github.com/nolimits4web/Swiper/commit/128827156b0f125a5f6ecf1409add4146fa3c989)), closes [Improve Accessibility Features #3149](https://github.com/nolimits4web/swiper/issues/3149)
> 
> ```
> <script setup lang="ts">
> import { Swiper, SwiperSlide } from "swiper/vue";
> import "swiper/css";
> import { A11y } from "swiper";
> </script>
> 
> <template>
>   <swiper
>     :modules="[A11y]"
>     :a11y="{
>       enabled: true,
>     }"
>   >
>     <swiper-slide v-for="i in [1, 2, 3, 4, 5]">
>       <div>
>         <input type="text" :value="i" />
>       </div>
>     </swiper-slide>
>   </swiper>
> </template>
> ```

This is not a fix. This is a bug. That's not the desired behavior.

**Comment by geekysaurabh001** [comment]
This isn't fixed. Adding a11y.enabled = true messes up everything else but fixes the display issue on link tabbed to different slide. So, any idea? Like it messes up role attributes of the html elements inside, aria label is messed up and replaced with 1/4, 2/4, etc.

**Comment by pixeldasher** [comment]
As of today, October 23rd of 2025, this bug still remains in SwiperJS 12.0.3 for me.

There are a couple of ways to work around this (mis)behavior, though an official solution would be nice.
Using the `inert` attribute on all non-active and non-visible slides would fix this rather quick.

I would be open to create and submit a PR, if necessary.
