### ISSUE TITLE
Deprecation warning: `Event.path` will be removed

### ISSUE THREAD

**Issue by vzikmund** [nolimits4web/swiper#6082]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://www.herni-kupony.cz/

### Bug description

Hello, 
we are using uriports.com to collect various data from our website. We started using Swiper and now we are having issue with notifications about deprecated function. **Please note, that this happens mostly in Chrome Mobile (Android) (97.1 %).**

![image](https://user-images.githubusercontent.com/85373369/191210731-251712f7-6ef4-4234-ba72-7052dcf1b957.png)

URL of script file: `https://www.herni-kupony.cz/assets/swiper/swiper-bundle.min.js `
Website URL: `https://www.herni-kupony.cz/`

With this deprecation notice are trigger two more notices from the same source-file. 

The next one is similar to the described one above:
```
WebFeature::kEventPath

'Event.path' is deprecated and will be removed in M109, around January 2023. Please use 'Event.composedPath()' instead. See https://www.chromestatus.com/feature/5726124632965120 for more details.
```

and the last one has only description `ExpectCTHeader` which I am not really sure what does that mean. 

May I kindly ask you if it is possible to fix this issue or do you have any advice how to suppress notification to be sent into the browser? Thank you for your time. 

### Swiper version

8.3.1

### Platform/Target and Browser Versions

Chrome Mobile 105

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by dijkermans** [comment]
should be fixed since 8.4.0
https://github.com/nolimits4web/swiper/releases

**Comment by vzikmund** [comment]
@dijkermans Thank you for your reply. Sadly i cannot confirm, that the deprecation notice is fixed with new version.  I updated package to version 8.4.2 but the error is still triggered. 

![image](https://user-images.githubusercontent.com/85373369/193260603-71e62c6b-6c5a-4f98-bc80-5bd3ef59fc16.png)

**Comment by nolimits4web** [comment]
Swiper already uses `composedPath`, but `event.path` is also still there and will be there for compatibility
