### ISSUE TITLE
SwiperJS Causes Crash on iPhone During Pinch-Zoom

### ISSUE THREAD

**Issue by itafraji** [nolimits4web/swiper#6922]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://swiperjs.com/demos

### Bug description

I've encountered an issue when using SwiperJS on iPhones. Whenever I try to use the pinch-zoom feature, the page crashes. Notably, this isn't just limited to my implementation — the same issue is observed on the official SwiperJS demo pages.

### Expected Behavior

The slides should zoom in/out smoothly without causing any disruptions.

### Actual Behavior

The entire page crashes upon attempting the pinch-zoom gesture.

### Swiper version

Lastest

### Platform/Target and Browser Versions

ios Safari 16.5

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [ ] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by aladeuil** [comment]
Hi,
It seems that this is only the case for the CSS version.
The biggest barrier to accessibility is that pinch zoom is impossible on all the others.

**Comment by nolimits4web** [comment]
Should be fixed in v11 + latest Safari

**Comment by jsefiani** [comment]
Hey @nolimits4web, it looks like this is still an issue. Are you sure this is fixed? I am using version 11.0.5 with React and CSS mode enabled.

**Comment by mannomion** [comment]
currently it sill bug on my website when swipe on safari. version using: ^11.1.3
