### ISSUE TITLE
Slide order and slide per column do not work properly in grid

### ISSUE THREAD

**Issue by maryma00012** [nolimits4web/swiper#7230]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/swiper-grid-forked-5tm9nl?file=%2Findex.html

### Bug description

The order of the slide displayed and the rows per column is not as expected. I am working on Vue using the swiper element but the same problem is shown in the simple html demo. In order to get 3 rows per column in 1 view, I have set 
1. slidesPerView: 1
2. grid: {
        rows: 3, 
        fill: "row"
}

However, only 2 rows are shown in the 1st page and the order is not in ascending order. Is there any solution on this issue?
I am looping through the slides therefore it is not possible to have the below as solution.
`<swiper-container class="mySwiper" init="false">`
`<swiper-slide>`
`<div>Slide 1</div>`
`<div>Slide 2</div>`
`<div>Slide 3</div>`
`</swiper-slide>`
`<swiper-slide>`
`<div>Slide 4</div>`
`</swiper-slide>`
`</swiper-container>`

### Expected Behavior

for 1st page
1  
2 
3

for 2nd page
4

### Actual Behavior

for 1st page
1  
3

for 2nd page
2
4

### Swiper version

^11.0.5

### Platform/Target and Browser Versions

Windows Chrome 119.0.6045.200 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by maryma00012** [comment]
In the end, it is just a CSS issue. After setting the height in the swiper container and set the fill to column, the issue is solved. If you swipe through the slides but it is swiped only half way through the slide, please set .swiper-wrapper { width: 0 !important; }, then the issue should be solved.

**Comment by jayna456** [comment]
@maryma00012, By applying your solution i.e. setting height and setting the fill to column, I can still see on first page 1 and 3.
