### ISSUE TITLE
With the latest update, the swipe function disappeared.

### ISSUE THREAD

**Issue by webgrill** [nolimits4web/swiper#7637]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/qd6gyz?file=%2Findex.html

### Bug description

With the latest update, the swipe function disappeared. If you insert clear text into a slide, it works, but if you insert an image, it doesn’t work.

### Swiper version

11.1.7

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/nolimits4web/swiper/blob/master/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://swiperjs.com/swiper-api).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a Swiper issue and not a framework-specific issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by nolimits4web** [comment]
It is fixed in 11.1.7

**Comment by bpdl1112** [comment]
HI I still get the bug :(, please check it: https://codesandbox.io/p/sandbox/p3f7rh
